#!/bin/sh

REGION=us-east-2
BUCKET=cobalt

function fail() {
    echo $2
    exit $1
}

echo "Creating S3 bucket..."

aws --endpoint-url=http://localstack-cobalt:4801 s3api create-bucket --bucket ${BUCKET} --region ${REGION} --create-bucket-configuration LocationConstraint=${REGION}
aws --endpoint-url=http://localstack-cobalt:4801 s3api put-bucket-acl --bucket ${BUCKET} --region ${REGION} --acl public-read
aws --endpoint-url=http://localstack-cobalt:4801 s3api put-bucket-cors --bucket ${BUCKET} --region ${REGION} --cors-configuration file://s3-bucket-cors.json

echo "Verifying SES identity..."

aws --endpoint-url=http://localstack-cobalt:4801 ses verify-email-identity --email-address no-reply@cobaltplatform.com --region ${REGION}

[ $? == 0 ] || fail 1 "Failed: AWS / ses / verify-email-identity"

# TODO: add SNS topic for listening to email bounces (and configuration set), see https://stackoverflow.com/a/75440135

echo "Localstack initialization complete."
