#!/bin/sh

REGION=us-east-2
BUCKET=cobalt

function fail() {
    echo $2
    exit $1
}

echo "Creating S3 bucket..."

aws --endpoint-url=http://localstack-cobalt:4801 s3api create-bucket --bucket ${BUCKET} --region ${REGION} --create-bucket-configuration LocationConstraint=${REGION}
aws --endpoint-url=http://localstack-cobalt:4801 s3api put-bucket-acl --bucket ${BUCKET} --region ${REGION} --acl public-read
aws --endpoint-url=http://localstack-cobalt:4801 s3api put-bucket-cors --bucket ${BUCKET} --region ${REGION} --cors-configuration file://s3-bucket-cors.json

echo "Verifying SES identity..."

aws --endpoint-url=http://localstack-cobalt:4801 ses verify-email-identity --email-address no-reply@cobaltplatform.com --region ${REGION}

[ $? == 0 ] || fail 1 "Failed: AWS / ses / verify-email-identity"

# TODO: add SNS topic for listening to email bounces (and configuration set), see https://stackoverflow.com/a/75440135

echo "Creating Secrets"

SECRET='{"com.cobaltplatform.api.jdbc.password":"password"}'

aws --endpoint-url=http://localstack-cobalt:4801 secretsmanager delete-secret --secret-id "cobalt-local-configuration"  --force-delete-without-recovery --region ${REGION} > /dev/null 2>&1
aws --endpoint-url=http://localstack-cobalt:4801 secretsmanager create-secret --name "cobalt-local-configuration"  --description "Local Secrets"  --secret-string ${SECRET} --region ${REGION}  1> /dev/null

aws --endpoint-url=http://localstack-cobalt:4801 secretsmanager delete-secret --secret-id "cobalt-local-cobalt-crt"  --force-delete-without-recovery --region ${REGION} > /dev/null 2>&1
aws --endpoint-url=http://localstack-cobalt:4801 secretsmanager create-secret --name "cobalt-local-cobalt-crt"  --description "Local Secrets"  --secret-binary fileb:///config/cobalt.crt --region ${REGION}  1> /dev/null

aws --endpoint-url=http://localstack-cobalt:4801 secretsmanager delete-secret --secret-id "cobalt-local-cobalt-pem"  --force-delete-without-recovery --region ${REGION} > /dev/null 2>&1
aws --endpoint-url=http://localstack-cobalt:4801 secretsmanager create-secret --name "cobalt-local-cobalt-pem"  --description "Local Secrets"  --secret-binary fileb:///config/cobalt.pem --region ${REGION}  1> /dev/null


aws --endpoint-url=http://localstack-cobalt:4801 secretsmanager delete-secret --secret-id "cobalt-local-cobalt-epic-nonprod-crt"  --force-delete-without-recovery --region ${REGION} > /dev/null 2>&1
aws --endpoint-url=http://localstack-cobalt:4801 secretsmanager create-secret --name "cobalt-local-cobalt-epic-nonprod-crt"  --description "Local Secrets"  --secret-binary fileb:///config/cobalt.epic.nonprod.crt --region ${REGION}  1> /dev/null

aws --endpoint-url=http://localstack-cobalt:4801 secretsmanager delete-secret --secret-id "cobalt-local-cobalt-epic-nonprod-pem"  --force-delete-without-recovery --region ${REGION} > /dev/null 2>&1
aws --endpoint-url=http://localstack-cobalt:4801 secretsmanager create-secret --name "cobalt-local-cobalt-epic-nonprod-pem"  --description "Local Secrets"  --secret-binary fileb:///config/cobalt.epic.nonprod.pem --region ${REGION}  1> /dev/null


aws --endpoint-url=http://localstack-cobalt:4801 secretsmanager delete-secret --secret-id "cobalt-local-cobalt-epic-prod-crt"  --force-delete-without-recovery --region ${REGION} > /dev/null 2>&1
aws --endpoint-url=http://localstack-cobalt:4801 secretsmanager create-secret --name "cobalt-local-cobalt-epic-prod-crt"  --description "Local Secrets"  --secret-binary fileb:///config/cobalt.epic.prod.crt --region ${REGION}  1> /dev/null

aws --endpoint-url=http://localstack-cobalt:4801 secretsmanager delete-secret --secret-id "cobalt-local-cobalt-epic-prod-pem"  --force-delete-without-recovery --region ${REGION} > /dev/null 2>&1
aws --endpoint-url=http://localstack-cobalt:4801 secretsmanager create-secret --name "cobalt-local-cobalt-epic-prod-pem"  --description "Local Secrets"  --secret-binary fileb:///config/cobalt.epic.prod.pem --region ${REGION}  1> /dev/null


aws --endpoint-url=http://localstack-cobalt:4801 secretsmanager delete-secret --secret-id "cobalt-local-cobalt-microsoft-crt"  --force-delete-without-recovery --region ${REGION} > /dev/null 2>&1
aws --endpoint-url=http://localstack-cobalt:4801 secretsmanager create-secret --name "cobalt-local-cobalt-microsoft-crt"  --description "Local Secrets"  --secret-binary fileb:///config/cobalt.microsoft.crt --region ${REGION}  1> /dev/null

aws --endpoint-url=http://localstack-cobalt:4801 secretsmanager delete-secret --secret-id "cobalt-local-cobalt-microsoft-pem"  --force-delete-without-recovery --region ${REGION} > /dev/null 2>&1
aws --endpoint-url=http://localstack-cobalt:4801 secretsmanager create-secret --name "cobalt-local-cobalt-microsoft-pem"  --description "Local Secrets"  --secret-binary fileb:///config/cobalt.microsoft.pem --region ${REGION}  1> /dev/null

echo "Localstack initialization complete."
