#!/bin/bash

echo "Bootstrapping Cobalt API..."

docker build -t cobalt-bootstrap -f ./docker/Dockerfile-bootstrap .
docker run --network localstack_default --rm cobalt-bootstrap:latest

echo "Bootstrap complete."