#!/bin/bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  # Special support for OS X
	TMPDIR=/private$TMPDIR docker compose -f localstack/docker-compose.yml up
else
	docker compose -f localstack/docker-compose.yml up
fi