FROM amazon/aws-cli:2.11.20

ENV AWS_DEFAULT_REGION=us-east-2
ENV AWS_ACCESS_KEY_ID=FAKE
ENV AWS_SECRET_ACCESS_KEY=FAKE

RUN amazon-linux-extras install postgresql12

COPY ./sql /sql/
COPY ./localstack /localstack/
COPY ./config/local /config

ENTRYPOINT []
CMD ["sh", "-c", "cd /localstack && ./initialize && cd /sql && ./recreate-bootstrap"]