#!/bin/bash

echo "Initializing IC DB..."

cd db
./ic-initial
cd ..

echo "Applying IC DB migrations..."

mvn package exec:java@migrate -Dmaven.test.skip=true

echo "Applying non-ebean migrations..."

cd db
./ic-updates
cd ..

echo "Setting up IC localstack..."

cd localstack
./bootstrap
cd ..