#!/bin/sh

PGPASSWORD=password psql -U postgres -h postgres-cobalt -p 5432 < initial/recreate.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < initial/install-versioning.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < initial/000-base-creates.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < initial/001-initial-inserts.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/002-click-tracking.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/003-session-expiration.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/004-activity-tracking.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/005-interaction.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/006-scheduled-messages.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/007-way2health.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/008-interaction-identifier.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/009-chaplain-rename.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/010-crisis-interaction-metadata.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/011-provider-specialties.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/012-fingerprinting.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/013-native-scheduling.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/014-provider-bio.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/015-appointment-update.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/016-account-role-request.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/016-local-only-account-role-request.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/017-account-session-for-intake.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/018-provider-active-flag.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/019-provider-find-indexing.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/020-interaction-generalization.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/021-screening.sql

if [ -f "initial/bootstrap.sql" ]; then
  echo "Loading bootstrap data..."
  PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < initial/bootstrap.sql
fi
