#!/bin/sh

PGPASSWORD=password psql -U postgres -h localhost -p 5501 < initial/recreate.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < initial/install-versioning.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < initial/000-base-creates.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < initial/001-initial-inserts.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/002-click-tracking.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/003-session-expiration.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/004-activity-tracking.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/005-interaction.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/006-scheduled-messages.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/007-way2health.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/008-interaction-identifier.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/009-chaplain-rename.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/010-crisis-interaction-metadata.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/011-provider-specialties.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/012-fingerprinting.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/013-native-scheduling.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/014-provider-bio.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/015-appointment-update.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/016-account-role-request.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/016-local-only-account-role-request.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/017-account-session-for-intake.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/018-provider-active-flag.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/019-provider-find-indexing.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/020-interaction-generalization.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/021-screening.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/022-provider-availability-history.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/023-institution-account-creation.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/024-account-email-verification.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/025-provider-scheduling-lead-time.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/026-screening-skip.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/027-capitalization-updates.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/028-institution-support-email.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/029-group-session-search.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/030-group-sessions-screening.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/031-group-session-request-updates.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/032-institution-updates.sql
PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < updates/033-mbi-screening-type.sql

if [ -f "initial/bootstrap.sql" ]; then
  echo "Loading bootstrap data..."
  PGPASSWORD=password psql -U cobalt -h localhost -p 5501 < initial/bootstrap.sql
fi