#!/bin/sh

PGPASSWORD=password psql -U postgres -h postgres-cobalt -p 5432 < initial/recreate.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < initial/install-versioning.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < initial/000-base-creates.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < initial/001-initial-inserts.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/002-click-tracking.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/003-session-expiration.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/004-activity-tracking.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/005-interaction.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/006-scheduled-messages.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/007-way2health.sql
PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < updates/008-interaction-identifier.sql

if [ -f "initial/bootstrap.sql" ]; then
  echo "Loading bootstrap data..."
  PGPASSWORD=password psql -U cobalt -h postgres-cobalt -p 5432 < initial/bootstrap.sql
fi
